# Generated by Django 4.1.1 on 2022-09-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
